language: c
services:
  - docker

git:
  depth: 1

env:
  matrix:
    - CC="clang" SCANBUILD="scan-build --status-bugs"
    - CC="gcc" SCANBUILD=""

after_failure:
  - cat tpm2-tcti-uefi-*/_build/sub/test-suite.log

install:
  - docker build -t tpm2-tcti-uefi:builder --target builder .

script:
  - docker run --rm -v $PWD:/src/tpm2-tcti-uefi -e CC="${CC}" -e SCANBUILD="${SCANBUILD}" tpm2-tcti-uefi:builder ./build.sh
  - docker run --rm -v $PWD:/src/tpm2-tcti-uefi tpm2-tcti-uefi:builder ./example/run.sh
